namespace ActPlcMitsubishi.Models
{
    public enum ActUnitType
    {
        CPU = 0x002C,
        CPU_FX5 = 0x2001
    }
    public enum ActProtocolType
    {
        TCP = 0x0005,
        UDP = 0x0008
    }
    public enum ActCpuType
    {
        Q03UDE = 0x0090,
        Q03UDV = 0x00D1,
        Q04UDV = 0x00D2,
        FX5U = 0x0210
    }

    public enum ActPortNumber
    {
        Q03UDV_PORT = 0x138F,
        FX5U_PORT = 0x15BA
    }

    public class Utils
    {
        public static string ReturnCode(uint errCode)
        {
            switch (errCode)
            {
                case 0x0000: return "Success";
                case 0x01010002: return "Timeout error.";
                case 0x01010005: return "Information error.";
                case 0x01010010: return "The PLC station number is incorrect and cannot communicate normally with the specified station number.";
                case 0x01010011: return "The mode error does not support the command.";
                case 0x01010012: return "The special unit configuration error.";
                case 0x01010013: return "Other data has failed for some reason and it is impossible to communicate.";
                case 0x01010018: return "The remote request error occurred in a non-communication path to perform remote operations.";
                case 0x01010020: return "The link error could not perform link communication.";
                case 0x01010021: return "The special unit bus is faulty. The special unit has no response.";
                case 0x01800001: return "No instruction error function is not supported.";
                case 0x01800002: return "The storage lock is in error.";
                case 0x01800003: return "Storage security error.";
                case 0x01800004: return "The DLL has loaded incorrectly.";
                case 0x01800005: return "Resource security error";
                case 0x01801001: return "The resource timed out error. The resource was not retrieved within the specified time.";
                case 0x01801002: return "The resource was not retrieved within the specified time.";
                case 0x01801003: return "The open command was not executed.";
                case 0x01801004: return "The type of open type is wrong.";
                case 0x01801005: return "The specified port is faulty.";
                case 0x01801006: return "An error occurred in the specified module.";
                case 0x01801007: return "Specify CPU error.";
                case 0x01801008: return "An error occurred while accessing the target station.";
                case 0x01801009: return "Registration failed. Failed to open registration data.";
                case 0x0180100A: return "The packet type is incorrect. The specified packet type is incorrect.";
                case 0x0180100B: return "The protocol type is incorrect. The specified protocol is incorrect.";
                case 0x0180100C: return "Search registration failed.";
                case 0x0180100D: return "GetProcAddress failed.";
                case 0x0180100E: return "The DLL was not loaded with an error.";
                case 0x0180100F: return "Another object is in execution and cannot execute the function because the dedicated control is running.";
                case 0x01802001: return "The device has an error and the device string specified in the function is not approved.";
                case 0x01802002: return "The device number error occurred, and the device string number specified in the function was not approved.";
                case 0x01802003: return "The program type is wrong.";
                case 0x01802004: return "And the check error occurred, and the received data and the check value were abnormal.";
                case 0x01802005: return "The size is wrong, the number of points specified in the function is not approved.";
                case 0x01802006: return "The batch number is incorrect, the batch number specified in the function's device string is not approved.";
                case 0x01802007: return "There was an error in receiving data, and the received data was abnormal.";
                case 0x01802008: return "Write protection error.";
                case 0x01802009: return "Error reading parameter.";
                case 0x0180200A: return "Error writing parameters.";
                case 0x0180200B: return "The PLC type does not match. The CPU model set in the property and the CPU model set in the communication, settings utility do not match the other communication terminal.";
                case 0x0180200C: return "Cancel request error, processing cancels request in progress.";
                case 0x0180200D: return "The drive name is incorrect, the specified drive name is incorrect.";
                case 0x0180200E: return "The first step error occurred and the specified start step was incorrect.";
                case 0x0180200F: return "The parameter type is incorrect and the parameter type is incorrect.";
                case 0x01802010: return "The file name is incorrect and the file name is incorrect.";
                case 0x01802011: return "Status error, registration/cancel/set status is incorrect.";
                case 0x01802012: return "Detail condition field error.";
                case 0x01802013: return "The step condition is wrong.";
                case 0x01802014: return "The bit device has an error.";
                case 0x01802015: return "Parameter setting error.";
                case 0x01802016: return "The specified telephone number is wrong. The function does not support the communication operation of the specified telephone number.";
                case 0x01802017: return "Keyword error.";
                case 0x01802018: return "Read/write error.";
                case 0x01802019: return "The refresh function has an error.";
                case 0x0180201A: return "The buffer access function has an error.";
                case 0x0180201B: return "Initial mode/end mode error.";
                case 0x0180201C: return "The clock data was written incorrectly. The specified clock data could not be written correctly due to a data error.";
                case 0x0180201D: return "Online clock data write error, clock data write failed. The clock data cannot be written because the PLC CPU is in the RUN state.";
                case 0x0180201E: return "The ROM drive has an error.";
                case 0x0180201F: return "An error occurred during the recording process and an invalid operation was performed in the record.";
                case 0x01802020: return "The initial I/O number error occurred and the initial I/O number value specified in the function was not approved.";
                case 0x01802021: return "The first address error occurred and the buffer address specified in the function was not approved.";
                case 0x01802022: return "The mode is wrong.";
                case 0x01802023: return "The SFC block number is incorrect.";
                case 0x01802024: return "The SFC step number is incorrect.";
                case 0x01802025: return "The step number is wrong.";
                case 0x01802026: return "Data error.";
                case 0x01802027: return "The system data is wrong.";
                case 0x01802028: return "The TC set value error.";
                case 0x01802029: return "Clean mode error.";
                case 0x0180202A: return "Signal flow error.";
                case 0x0180202B: return "Version control error.";
                case 0x0180202C: return "Unregistered monitoring error.";
                case 0x0180202D: return "Error in PI type.";
                case 0x0180202E: return "The PI number is wrong.";
                case 0x0180202F: return "The number of PIs is wrong.";
                case 0x01802030: return "The shift was wrong.";
                case 0x01802031: return "The file type is incorrect.";
                case 0x01802032: return "The specified unit has an error.";
                case 0x01802033: return "Error check mark error.";
                case 0x01802034: return "Step by step RUN operation error.";
                case 0x01802035: return "Step by step RUN data error.";
                case 0x01802036: return "An error occurred during step-by-step RUN.";
                case 0x01802037: return "The program was written to the E2PROM during communication execution.";
                case 0x01802038: return "Clock data read/write error, PLC CPU without clock device performs clock data read/write function.";
                case 0x01802039: return "The record did not complete the error.";
                case 0x0180203A: return "The registration clear flag has an error.";
                case 0x0180203B: return "Operation error.";
                case 0x0180203C: return "The number of exchanges has gone wrong.";
                case 0x0180203D: return "The specified number of loops is wrong.";
                case 0x0180203E: return "Regain selected data.";
                case 0x0180203F: return "The number of SFC loops has failed.";
                case 0x01802040: return "Motion PLC error.";
                case 0x01802041: return "Motion PLC communication error.";
                case 0x01802042: return "Fixed execution time setting error.";
                case 0x01802043: return "The function number of each function is incorrect.";
                case 0x01802044: return "The system information indicates an error.";
                case 0x01802045: return "There is an error in the registration condition.";
                case 0x01802046: return "The function number is wrong.";
                case 0x01802047: return "RAM drive error.";
                case 0x01802048: return "The boot terminal ROM drive has an error.";
                case 0x01802049: return "The boot terminal transfer mode specification error.";
                case 0x0180204A: return "The memory is out of error.";
                case 0x0180204B: return "An error occurred while backing up the drive ROM.";
                case 0x0180204C: return "The block size is wrong.";
                case 0x0180204D: return "The separation error occurred in the RUN state.";
                case 0x0180204E: return "The unit has been registered with an error.";
                case 0x0180204F: return "The password registration data is full.";
                case 0x01802050: return "The password was not registered.";
                case 0x01802051: return "The remote password is incorrect.";
                case 0x01802052: return "The IP address is incorrect.";
                case 0x01802053: return "The timeout value exceeded the range error.";
                case 0x01802054: return "The command was not retrieved.";
                case 0x01802055: return "Error in executing record type";
                case 0x01802056: return "Version error";
                case 0x01802057: return "The tracking cable is faulty and the tracking cable is faulty. The PLC CPU is in the error state.";
                case 0x01808001: return "The error is opened multiple times, and the open function is executed again after opening.";
                case 0x01808002: return "The channel number specification error occurred, and the port number value set in the attribute and the communication settings utility was not approved.";
                case 0x01808003: return "The driver is not running and the network board driver is not running.";
                case 0x01808004: return "An error occurred while generating an overlap event.";
                case 0x01808005: return "Generating MUTEX error creates MUTEX for dedicated control failure.";
                case 0x01808006: return "Generating a web interface program error, unable to create a web interface program";
                case 0x01808007: return "An error occurred while generating the web interface program. The creation of the web interface program failed.";
                case 0x01808008: return "The port connection is wrong, the connection failed to be established. The other end has no response.";
                case 0x01808009: return "The COM port control close error occurred and the COM port could not be operated. The COM port number could not be copied. The SOCKET port number could not be copied.";
                case 0x0180800A: return "The buffer size setting error occurred, setting the COM port buffer size failed.";
                case 0x0180800B: return "The error in getting the DCB value failed to get the COMB value of the COM port.";
                case 0x0180800C: return "The DCB setting error failed to set the COM port DCB value.";
                case 0x0180800D: return "Timeout value setting error, setting COM port timeout value failed.";
                case 0x0180800E: return "Open shared memory error, failed to open shared memory.";
                case 0x01808101: return "Repeat close error.";
                case 0x01808102: return "The shutdown control error occurred and the COM port control failed to close.";
                case 0x01808103: return "Driver close error, shutdown driver control failed.";
                case 0x01808104: return "Overlap event close error.";
                case 0x01808105: return "Mutex control close error.";
                case 0x01808106: return "COM port control close error.";
                case 0x01808201: return "Send error, sending data failed.";
                case 0x01808202: return "The send data size is wrong and the data transmission failed.";
                case 0x01808203: return "Clear queue error, failed to clear COM port queue.";
                case 0x01808301: return "Receive error, receiving data failed.";
                case 0x01808302: return "No error sent.";
                case 0x01808303: return "Regaining errors in overlapping events.";
                case 0x01808304: return "The receive buffer capacity is insufficient and the received data exceeds the receive buffer capacity prepared by the system.";
                case 0x01808401: return "Control error, COM port communication control change failed.";
                case 0x01808402: return "Signal line control error.";
                case 0x01808403: return "The signal line designation error occurred and the COM port communication control change failed.";
                case 0x01808404: return "The open command was not executed.";
                case 0x01808405: return "Communication parameter error, the combination of data bit and stop bit in the attribute is not approved.";
                case 0x01808406: return "The specified transfer rate value is incorrect, and the transfer rate in the attribute is not approved.";
                case 0x01808407: return "The data length is incorrect. The data bit value in the attribute is not approved.";
                case 0x01808408: return "The specified parity error occurred and the parity value in the attribute was not approved.";
                case 0x01808409: return "The specified stop bit error occurred and the stop bit value in the attribute was not approved.";
                case 0x0180840A: return "The communication control setting is incorrect, and the control value in the attribute is not approved.";
                case 0x0180840B: return "Timeout error, after the timeout period, the data has not been received.";
                case 0x0180840C: return "Connection error.";
                case 0x0180840D: return "Repeat connection error.";
                case 0x0180840E: return "The connection failed and the web interface program connection failed.";
                case 0x0180840F: return "The signal line status failed to get the COM port signal line status failed.";
                case 0x01808410: return "The CD signal line is OFF, and the CD signal is OFF at the other communication end.";
                case 0x01808411: return "The password does not match.";
                case 0x01808412: return "TEL communication error.";
                case 0x01808501: return "The USB driver failed to load and the USB driver failed to load.";
                case 0x01808502: return "The USB driver connection error occurred and the connection to the USB driver failed.";
                case 0x01808503: return "USB driver sent error, data transmission failed";
                case 0x01808504: return "The USB driver received an error and data reception failed.";
                case 0x01808505: return "USB driver timeout error.";
                case 0x01808506: return "USB driver initialization error, USB driver initialization failed.";
                case 0x01808507: return "USB other errors, errors related to data transmission/reception.";
                case 0x02000001: return "The number of points exceeds the range error, and the number of points registered in the monitoring server is too high.";
                case 0x02000002: return "An error occurred while creating shared memory. Failed to create shared memory.";
                case 0x02000003: return "An error occurred while accessing shared memory.";
                case 0x02000004: return "Protected memory error, protection monitoring server memory failed.";
                case 0x02000005: return "The device is not registered with an error and the monitor is not registered.";
                case 0x02000006: return "The monitoring server failed to start and the monitoring server did not start.";
                case 0x02000010: return "The retrieval device value is incorrect and the monitoring is not completed.";
                case 0x03000001: return "The command is not supported and the command is not supported.";
                case 0x03000002: return "Lock memory error, lock memory failed.";
                case 0x03000003: return "Protected memory error, failed to protect memory.";
                case 0x03000004: return "Error reading DLL, failed while reading DLL.";
                case 0x03000005: return "Protect resource error and fail when protecting resources.";
                case 0x03010001: return "The file creation error occurred and the file creation failed.";
                case 0x03010002: return "The file opening error occurred, opening the file failed.";
                case 0x03010003: return "The buffer size is incorrect, the specified buffer size is incorrect or not large enough.";
                case 0x03010004: return "The SIL statement format is wrong, and the SIL statement format is incorrect.";
                case 0x03010005: return "The file name is incorrect. The specified file name is too long.";
                case 0x03010006: return "The file does not have an error and the specified file does not exist.";
                case 0x03010007: return "The file structure is faulty and the data structure in the specified file is incorrect.";
                case 0x03010008: return "The file has an error and the specified file already exists.";
                case 0x03010009: return "The file does not have an error and the specified file does not exist.";
                case 0x0301000A: return "File deletion error, the specified file could not be deleted.";
                case 0x0301000B: return "Repeat open error, the specified project has been opened twice.";
                case 0x0301000C: return "The file name is incorrect and the specified file name is incorrect.";
                case 0x0301000D: return "Error reading file, failed to read file.";
                case 0x0301000E: return "Error writing to file, writing to file failed.";
                case 0x0301000F: return "Failed to find file, failed to find file.";
                case 0x03010010: return "The file was closed and the file failed to close.";
                case 0x03010011: return "The folder creation error occurred, creating a folder failed.";
                case 0x03010012: return "Copy file error, copy file failed.";
                case 0x03010013: return "The project path is wrong and the project path length is incorrect.";
                case 0x03010014: return "The project type is wrong and the project type is incorrect.";
                case 0x03010015: return "The file type is incorrect and the file type is incorrect.";
                case 0x03010016: return "Subfile type error, subfile type is incorrect.";
                case 0x03010017: return "Insufficient disk space error, insufficient disk space.";
                case 0x03020002: return "Repeat open error, open database product multiple times.";
                case 0x03020003: return "The error has not been opened and the database product is not open.";
                case 0x03020004: return "The decompression error occurred and the database product could not be uncompressed.";
                case 0x03020010: return "Parameter error, the parameters of the database product are incorrect.";
                case 0x03020011: return "The code is wrong and the code parameters are incorrect.";
                case 0x03020012: return "The specified manufacturer has an error and the manufacturer parameters are incorrect.";
                case 0x03020013: return "The specified unit is faulty and the unit parameters are incorrect.";
                case 0x03020014: return "The SQL parameter is incorrect, the SIL and SQL parameters of the database product are incorrect.";
                case 0x03020015: return "The SIL statement format is wrong, and the SIL statement format is incorrect.";
                case 0x03020016: return "The input field is incorrect and the input field is incorrect.";
                case 0x03020050: return "The error in creating record data failed to rebuild the database product record data.";
                case 0x03020060: return "An error occurred in retrieving record data. Failed to retrieve database product record data.";
                case 0x03020061: return "The last record was logged. When the current record is the last record, the next one cannot be retrieved.";
                case 0x03FF0000: return "Initialization error.";
                case 0x03FF0001: return "No initialization error.";
                case 0x03FF0002: return "Repeat initialization error.";
                case 0x03FF0003: return "Workspace initialization error.";
                case 0x03FF0004: return "Database initialization error.";
                case 0x03FF0005: return "The recording device was initialized incorrectly.";
                case 0x03FF0006: return "An error occurred while closing the database.";
                case 0x03FF0007: return "Error closing the recording device";
                case 0x03FF0008: return "There was an error opening the database and the database was not open.";
                case 0x03FF0009: return "The recording device did not open and the recording device did not turn on.";
                case 0x03FF000A: return "The initialization table failed and the initialization of the TtableInformation table failed.";
                case 0x03FF000B: return "An initialization table error occurred, initializing the TfieldInformation table failed.";
                case 0x03FF000C: return "Initialization table error, initialization of the TrelationInformation table failed.";
                case 0x03FF000D: return "An initialization table error occurred, initializing the Tlanguage table failed.";
                case 0x03FF000E: return "Initialization table error, initialization Tmaker table failed.";
                case 0x03FF000F: return "An initialization table error occurred, initializing the TOpenDatabase table failed.";
                case 0x03FF0010: return "The segment value is wrong.";
                case 0x03FF0011: return "The segment value is wrong.";
                case 0x03FF0012: return "The exit error occurred and the logout failed.";
                case 0x03FF0100: return "The move record failed and the move record failed.";
                case 0x03FF0101: return "The number of records retrieved was incorrect, and the number of records retrieved failed.";
                case 0x03FF0110: return "Error retrieving section value, failed to retrieve section value";
                case 0x03FF0111: return "Set segment value error, setting segment value failed.";
                case 0x03FFFFFF: return "Other mistakes.";
                case 0x04000001: return "No command error, the specified CPU model cannot be used for processing.";
                case 0x04000002: return "Lock memory error, lock memory failed.";
                case 0x04000003: return "Protected memory error, failed to protect memory.";
                case 0x04000004: return "The internal server loaded DLL error failed to start the internal server.";
                case 0x04000005: return "Protecting resources and making mistakes in protecting resources.";
                case 0x04000006: return "The error loading the main object failed to read the file.";
                case 0x04000007: return "Loading conversion table error, reading table data failed.";
                case 0x04000100: return "Incorrect midsize size error.";
                case 0x04010001: return "The intermediate code is not converted incorrectly. Converting a command to machine code exceeds 256 bytes.";
                case 0x04010002: return "The intermediate code completed an error and the mid-code conversion of the code abruptly terminated.";
                case 0x04010003: return "The intermediate code is not fully errored, and the intermediate code conversion of the code is not sufficient.";
                case 0x04010004: return "The intermediate code data is wrong, and the intermediate code conversion is incorrect.";
                case 0x04010005: return "The intermediate code structure is wrong, and the number of steps in the intermediate code is incorrect.";
                case 0x04010006: return "The number of steps is incorrect, indicating that the number of steps in the intermediate code is incorrect.";
                case 0x04010007: return "There is insufficient error in the storage space of the machine code, and the storage space of the machine code is insufficient.";
                case 0x04010008: return "Other errors, (other errors that occur when converting from intermediate code to machine code.)";
                case 0x04011001: return "The machine code has not been converted with an error. Converting a command to the intermediate code exceeds 256 bytes.";
                case 0x04011002: return "The machine code completed an error and the machine code conversion abruptly terminated.";
                case 0x04011003: return "Anomalous machine code error, conversion machine code is abnormal, cannot be converted.";
                case 0x04011004: return "The intermediate code storage space is insufficient, the intermediate code storage area is insufficient.";
                case 0x04011005: return "Other errors, other errors caused by the conversion of machine code into intermediate code.";
                case 0x04020001: return "Other errors generated by machine code conversion to intermediate code. Convert a command to intermediate code over 256 bytes.";
                case 0x04020002: return "No input error, insufficient input code list.";
                case 0x04020003: return "The command error occurred and the command name for the conversion code list was incorrect.";
                case 0x04020004: return "The device has an error and the device name of the conversion code list is incorrect.";
                case 0x04020005: return "The device number error occurred, and the device number of the conversion code list exceeded the range.";
                case 0x04020006: return "The conversion error occurred and the list of converted codes could not be recognized.";
                case 0x04020007: return "The text data is wrong and the code list conversion is incorrect.";
                case 0x04020008: return "The SFC output operation error occurred, and the output command to operate the SFC is incorrect.";
                case 0x04020009: return "The SFC shift condition is incorrect and the SFC move condition command is incorrect.";
                case 0x0402000A: return "The interline statement error occurred, and the statement entered between the program lines was incorrect.";
                case 0x0402000B: return "The P.I statement is in error and the input P.I statement is incorrect.";
                case 0x0402000C: return "The comment is incorrect and the comment entered is incorrect.";
                case 0x0402000D: return "The comment is incorrect and the comment entered is incorrect.";
                case 0x0402000E: return "Other errors, (other errors that occur when the list is converted to intermediate code.)";
                case 0x04021001: return "The intermediate code did not convert error. Converting a command to the code list is more than 256 bytes.";
                case 0x04021002: return "The intermediate code area is full and the converted intermediate code area is full.";
                case 0x04021003: return "The command error occurred. The command specified by the converted intermediate code is incorrect.";
                case 0x04021004: return "The device has an error and the device specified in the converted intermediate code is incorrect.";
                case 0x04021005: return "The intermediate code is wrong, and the converted intermediate code structure is incorrect.";
                case 0x04021006: return "The list storage space is insufficient, there is not enough space to store the conversion code list.";
                case 0x04021007: return "Other errors, (the intermediate code is converted to other errors that occur when the list is created.)";
                case 0x04030001: return "There is no conversion error, there is not enough storage space for the conversion intermediate code.";
                case 0x04030002: return "The error circuit was created and the character memory circuit was not completed in a sequence program.";
                case 0x04030003: return "The specified circuit size is out of range and the specified circuit size is too large.";
                case 0x04030004: return "Incorrect return circuit error, no consistency before and after returning to the circuit. The set return circuit is too high.";
                case 0x04030005: return "Other errors, (other errors that occur when character memory is converted to intermediate code.)";
                case 0x04031001: return "No conversion error, the specified character memory size (portrait/landscape) is incorrect.";
                case 0x04031002: return "The exception command code is incorrect, and the converted command intermediate code is incorrect.";
                case 0x04031003: return "The error circuit was created and cannot be converted to a sequencer circuit. There is no END command.";
                case 0x04031004: return "The specified circuit size is out of range error, the specified circuit size is too large.";
                case 0x04031005: return "Significant mistakes, major mistakes.";
                case 0x04031006: return "There is not enough error in the number of memory blocks, and there is not enough space to store the converted character memory circuit block.";
                case 0x04031007: return "Find circuit block error, data is interrupted in the circuit block.";
                case 0x04031008: return "Other errors, (other errors that occur when the intermediate code is converted to character memory.)";
                case 0x04040001: return "CAD data error has no CAD data to convert. CAD data format is incorrect.";
                case 0x04040002: return "The output data is incorrect. The input CAD data and the output CAD data type do not match.";
                case 0x04040003: return "Load library error, loader library failed.";
                case 0x04040004: return "The storage space is protected incorrectly and there is not enough protected space to store the converted data.";
                case 0x04040005: return "No error in END command, no END command in CAD data conversion.";
                case 0x04040006: return "An error in the exception command code, the command code is abnormal in the CAD data conversion.";
                ////////////////////////////////////////////////////////////////////////////////
                case 0x04040007: return "The device number is incorrect and the device number is out of range.";
                case 0x04040008: return "The step number is wrong and the step number is out of range.";
                case 0x04040009: return "The specified circuit size is out of range error, one circuit block is too large.";
                case 0x0404000A: return "The return circuit is faulty and the return circuit is incorrect.";
                case 0x0404000: return "b creates an error in the wrong circuit and the circuit data is incorrect.";
                case 0x0404000C: return "SFC data error, conversion SFC data is incorrect.";
                case 0x0404000D: return "List data error, conversion list data is incorrect.";
                case 0x0404000E: return "Comment data error, conversion comment data is incorrect.";
                case 0x0404000F: return "The statement was incorrect and the conversion declaration data is incorrect.";
                case 0x04040010: return "Other errors, (other errors that occur when the CAD code is converted to intermediate code.)";
                case 0x04041001: return "The intermediate code data is wrong, there is no intermediate code to convert.";
                case 0x04041002: return "The CAD data type is incorrect, the input CAD data and the output CAD data type do not match.";
                case 0x04041003: return "The library failed and the loader library failed.";
                case 0x04041004: return "The input data is insufficient, and the converted data is insufficient.";
                case 0x04041005: return "There is insufficient storage space and there is not enough space to store the CAD data to be converted.";
                case 0x04041006: return "There is an error with the END command, and there is no END command in the CAD data to be converted.";
                case 0x04041007: return "An error in the exception command code, there is an exception command code in the CAD data to be converted.";
                case 0x04041008: return "The device number is incorrect and the device number is out of range.";
                case 0x04041009: return "The step number is wrong and the step number is out of range.";
                case 0x0404100A: return "The specified circuit size is out of range error, 1 circuit block is too large.";
                case 0x0404100: return "b returns a circuit error and the return circuit is incorrect.";
                case 0x0404100C: return "The error circuit was created and the circuit data is incorrect.";
                case 0x0404100D: return "The SFC data is incorrect and the SFC data to be converted is incorrect.";
                case 0x0404100E: return "List data error, the list data to be converted is incorrect.";
                case 0x0404100F: return "Comment data error, conversion comment data is incorrect.";
                case 0x04041010: return "The statement was incorrect and the conversion declaration data is incorrect.";
                case 0x04041011: return "Other errors, (other errors that occur when the CAD code is converted to intermediate code.)";
                case 0x040A0001: return "The intermediate code storage space is insufficient, and the data space after the storage conversion is insufficient.";
                case 0x040A0002: return "Insufficient storage of SFC information space";
                case 0x040A0003: return "Conversion error";
                case 0x040A0004: return "No error with SFC program";
                case 0x040A1001: return "Unused step / no output error";
                case 0x040A1002: return "The step number is out of range error";
                case 0x040A1003: return "Unused step / no output error";
                case 0x040A1004: return "Transmission number is out of range";
                case 0x040A1005: return "Error exceeding the maximum number";
                case 0x040A1006: return "Macro controller program space error";
                case 0x040A1007: return "No error with SFC program";
                case 0x040B0001: return "The intermediate code storage space is insufficient, and the data space after the storage conversion is insufficient.";
                case 0x040B0002: return "Conversion error";
                case 0x040B1001: return "Failed to create step start table";
                case 0x040B1002: return "Error reading step information";
                case 0x040B1003: return "Step number error";
                case 0x040B1004: return "Read operation output failed / transmission intermediate code status error";
                case 0x040B1005: return "Failed to protect internal work area";
                case 0x040B1006: return "Setting the maximum value of the X direction error in the character memory";
                case 0x040B1007: return "Insufficient internal work area error";
                case 0x040B1008: return "Stack Overflow, Exception Character Memory";
                case 0x040B1009: return "The number of memory blocks is insufficient";
                case 0x040B100A: return "No error with SFC program";
                case 0x04050001: return "The specified string exception error occurred, and the specified device string is incorrect.";
                case 0x04050002: return "The number of device points is incorrect, and the number of device points is out of range.";
                case 0x04050003: return "Other errors, (when the device string is converted to the device intermediate code)";
                case 0x04051001: return "The device name is incorrect, and the specified device intermediate code classification is incorrect.";
                case 0x04051002: return "The device name is incorrect, and the specified extension specification device intermediate code classification is incorrect.";
                case 0x04051003: return "Other errors, (when the device intermediate code is converted into a device string)";
                case 0x04052001: return "The specified string exception error occurred, and the specified device string is incorrect.";
                case 0x04052002: return "The number of device points is incorrect, and the number of device points is out of range.";
                case 0x04052003: return "Other errors, (the device string is converted to the device when it inherits the code)";
                case 0x04053001: return "Device inheritance error, the specified device intermediate code classification is incorrect.";
                case 0x04053002: return "Device inheritance error, the specified extension specification device intermediate code classification is incorrect.";
                case 0x04053003: return "Device inheritance error, device specified component is not rectified correctly.";
                case 0x04053004: return "Device inheritance error, the rectification of the specified device is not correct.";
                case 0x04053005: return "Other errors, (the device generated when the device inherits the code into a device string)";
                case 0x04064001: return "The device intermediate code is abnormal, and the middle code of the device is incorrect.";
                case 0x04064002: return "Other errors, (other errors caused when the device intermediate code is converted to the device name)";
                case 0x04065001: return "The device name error occurred, and the specified device intermediate code classification is incorrect.";
                case 0x04065002: return "The device name error is abnormal, and the specified extension specification device intermediate code classification is incorrect.";
                case 0x04065003: return "Other errors, (other errors that occur when the device name is converted to the intermediate code.)";
                case 0x04066001: return "The device intermediate code is incorrect, and the middle code of the device is incorrect.";
                case 0x04066002: return "Other errors, (the device intermediate code is converted into a device inheritance code when it is generated";
                case 0x04067001: return "Device inheritance error, the specified device intermediate code classification is incorrect.";
                case 0x04067002: return "Device inheritance error, the specified extension specification device intermediate code classification is incorrect.";
                case 0x04067003: return "The device inheritance error occurred, and the correction portion of the specified device is incorrect.";
                case 0x04067004: return "The device inheritance error occurred, and the correction portion of the specified extended device is incorrect.";
                case 0x04067005: return "Other errors, (other errors occur when the device representation code is converted to the device middle code)";
                case 0x04070001: return "The public data conversion error occurred, and the input device comment data is incorrect.";
                case 0x04070002: return "There is insufficient public data and the conversion data is insufficient.";
                case 0x04070003: return "There is not enough storage area and there is not enough data storage area.";
                case 0x04071001: return "The conversion of PLC data is incorrect and the input device comment data is incorrect.";
                case 0x04071002: return "Insufficient PLC data error, insufficient data to be converted.";
                case 0x04071003: return "There is not enough storage area and there is not enough data storage area.";
                case 0x04072001: return "Open error, failed to create a conversion target.";
                case 0x04072002: return "PLC type error, the specified PLC type does not exist.";
                case 0x04072003: return "No conversion error, conversion target does not exist.";
                case 0x04072004: return "The input data is incorrect and the input data is incorrect.";
                case 0x04073001: return "Common program data conversion error";
                case 0x04073002: return "Common program data conversion error";
                case 0x04073101: return "PLC program data conversion error";
                case 0x04074001: return "Common data parameter error";
                case 0x04074002: return "The public network parameter data is incorrect, the parameter block exists, but its internal data is not set.";
                case 0x04074101: return "PLC parameter data error";
                case 0x04074102: return "PLC network parameter data error, parameter block exists, but its internal data is not set.";
                case 0x04074103: return "Error error";
                case 0x04074201: return "The specified network type is incorrect. The specified PLC does not support this network type.";
                case 0x04074202: return "The parameter block number is incorrect. The block corresponding to the specified parameter block number does not exist.";
                case 0x04074203: return "The parameter block content is in error and is different from the specified supported content.";
                case 0x04074204: return "Parameter block information error, the specified block number does not exist.";
                case 0x04074205: return "The default parameter block exception, the specified block number does not exist.";
                case 0x04074301: return "Error while converting public parameter block";
                case 0x04074302: return "An error occurred in the public parameter block No. 1001, and the RUN-PAUSE setting value is incorrectly marked.";
                case 0x04074303: return "Error in public parameter block No. 1003";
                case 0x04074304: return "Error in public parameter block No. 1008";
                case 0x04074305: return "Error in public parameter block 1100";
                case 0x04074306: return "An error occurred in the public parameter block in 2001. The specified device intermediate code does not exist.";
                case 0x04074307: return "Error in public parameter block No. 3000";
                case 0x04074308: return "Error in public parameter block No. 3002";
                case 0x04074309: return "An error occurred in the public parameter block No. 3004, and the alarm display mode setting is incorrect.";
                case 0x0407430A: return "An error occurred in the public parameter block No. 4000, and I/O allocation data was not created.";
                case 0x0407430: return "An error occurred in public parameter block b5000. The specified network is not supported.";
                case 0x0407430C: return "An error occurred in the public parameter block No. 5001. When accessing other exchanges, the effective unit number is not set.";
                case 0x0407430D: return "Error in public parameter block No. 5002";
                case 0x0407430E: return "Error in public parameter block No. 5003";
                case 0x0407430F: return "Error in public parameter block 5NM0";
                case 0x04074310: return "Error in public parameter block 5NM1";
                case 0x04074311: return "Error in public parameter block 5NM2";
                case 0x04074312: return "Error in public parameter block 5NM3";
                case 0x04074313: return "Error in the public parameter block No. 6000";
                case 0x04074314: return "Error in the public parameter block of FF18, the link parameter capacity is not set.";
                case 0x04074315: return "An error occurred in the common parameter block of FF25, and the calculation check circuit was not set.";
                case 0x04074316: return "An error occurred in the public parameter block FF30, and the sample data path was not created.";
                case 0x04074317: return "An error occurred in the common parameter block of FF31, and the status latch data was not created.";
                case 0x04074318: return "An error occurred in the public parameter block of FF42, and the number of timer processing points was not set.";
                case 0x04074319: return "An error occurred in the common parameter block No. FF30, and the device value set for the specified extended timer does not exist.";
                case 0x0407431A: return "Error in public parameter block FF44";
                case 0x0407431: return "Error in public parameter block bFF45";
                case 0x0407431C: return "An error occurred in the public parameter block of FF60, and the terminal setting was not set.";
                case 0x0407431D: return "An error occurred in the public parameter block of FF70, and the user release area was not set.";
                case 0x04074401: return "Error converting PLC parameter block";
                case 0x04074402: return "Error in PLC parameter block No. 1001";
                case 0x04074403: return "Error in PLC parameter block No. 1003";
                case 0x04074404: return "Error in PLC parameter block No. 1008";
                case 0x04074405: return "Error in PLC parameter block No. 1100";
                case 0x04074406: return "Error in PLC parameter block No. 2001";
                case 0x04074407: return "Error in PLC parameter block No. 3000";
                case 0x04074408: return "Error in PLC parameter block No. 3002";
                case 0x04074409: return "Error in PLC parameter block No. 3004";
                case 0x0407440A: return "Error in PLC parameter block No. 4000";
                case 0x0407440: return "An error occurred in the PLC parameter block b5000. The specified network type is not supported.";
                case 0x0407440C: return "Error in PLC parameter block No. 5001";
                case 0x0407440D: return "Error in PLC parameter block No. 5002";
                case 0x0407440E: return "Error in PLC parameter block No. 5003";
                case 0x0407440F: return "An error occurred in the PLC parameter block No. 5NM0. The specified network type is not supported.";
                case 0x04074410: return "Error in PLC Parameter Block 5NM1";
                case 0x04074411: return "An error occurred in the 5NM2 PLC parameter block. The specified network type is not supported.";
                case 0x04074412: return "Error in PLC Parameter Block 5NM3";
                case 0x04074413: return "Error in PLC parameter block No. 6000";
                case 0x04074414: return "Error in PLC parameter block of FF18";
                case 0x04074415: return "Error in PLC parameter block of FF25";
                case 0x04074416: return "Error in PLC parameter block of FF30";
                case 0x04074417: return "Error in PLC parameter block of FF31";
                case 0x04074418: return "Error in PLC parameter block of FF42";
                case 0x04074419: return "Error in PLC parameter block of FF43";
                case 0x0407441A: return "Error in PLC parameter block of FF44";
                case 0x0407441: return "Error in PLC parameter block of bFF45";
                case 0x0407441C: return "Error in PLC parameter block of FF60";
                case 0x0407441D: return "Error in PLC parameter block of FF70";
                case 0x04075001: return "The public data conversion error occurred and the conversion of the device memory was failed.";
                case 0x04075002: return "The public data conversion error occurred and the data portion of the device memory was converted.";
                case 0x04075003: return "The public data conversion error occurred, and the data portion of the device memory does not exist.";
                case 0x04075101: return "PLC data conversion error, failed to convert the setting portion of the device memory.";
                case 0x04075102: return "PLC data conversion error, failed to convert the data portion of the device memory.";
                case 0x04076001: return "The public data conversion error occurred and the setting part of the device comment failed.";
                case 0x04076002: return "The public data conversion error occurred and the data portion of the device comment failed.";
                case 0x04076101: return "PLC data conversion error, failed to convert the setting part of the device comment.";
                case 0x04076102: return "PLC data conversion error, failed to convert the setting part of the device comment.";
                case 0x04077001: return "The public data conversion error occurred and the conversion of the sample path was partially failed.";
                case 0x04077002: return "The public data conversion error occurred and the data portion of the sample path failed.";
                case 0x04077101: return "PLC data conversion error, failed to convert the setting part of the sample path.";
                case 0x04077102: return "PLC data conversion error, failed to convert the data portion of the sample path.";
                case 0x04078001: return "The public data conversion error occurred and the conversion status latched part failed.";
                case 0x04078002: return "The public data conversion error occurred and the conversion of the data portion of the state latch failed.";
                case 0x04078101: return "PLC data conversion error, failed to convert the setting part of the status latch.";
                case 0x04078102: return "PLC data conversion error, failure to convert the data portion of the status latch.";
                case 0x04079101: return "PLC data conversion failure history error";
                case 0x0407A101: return "PLC file list data conversion error";
                case 0x0407B101: return "PLC data conversion information error";
                case 0x0407C001: return "Indirect address conversion is an error in the device name, and the device name storage area is not protected.";
                case 0x0407C002: return "The device name was converted to an indirect address error, and the indirect address storage area was not protected.";
                case 0x0407C003: return "Indirect address translation is a device request error, there is no protection device to display the memory area.";
                case 0x0407C004: return "Device request conversion to indirect address error, indirect address storage is not protected.";
                case 0x0407C005: return "Indirect address conversion to device string error, device string storage area is not protected.";
                case 0x0407C006: return "The device string is converted to the intermediate code error, and the indirect address storage area is not protected.";
                case 0x0407C007: return "The intermediate code is converted to the device name error, and the device name storage area is not protected.";
                case 0x0407C008: return "The device name is converted to the intermediate code error, and the intermediate code storage area is not protected.";
                case 0x0407C009: return "An error occurred while converting the intermediate code to the device request, and the unprotected device requested the memory area.";
                case 0x0407C00A: return "Device Representation converted to intermediate code error, intermediate code storage area is not protected.";
                case 0x0407C00: return "The intermediate code is converted to an indirect address error, and the indirect address storage area is not protected.";
                case 0x0407C00C: return "Indirect address conversion to intermediate code error, intermediate code storage area is not protected.";
                case 0x0407C00D: return "PLC type error, the specified PLC type is not supported.";
                case 0x0407C00E: return "The device string is incorrect and the specified device is not supported.";
                case 0x0407C00F: return "The device string error occurred, and the device string and type were specified incorrectly.";
                case 0x0407C010: return "Device error, the specified PLC does not support the specified device.";
                case 0x0407C011: return "PLC type error, the specified PLC type is not supported.";
                case 0x0407C012: return "The device is out of range error. For the AnA system, the specified device exceeds the AnA system.";
                case 0x0407D001: return "The public data conversion error occurred, and the conversion SFC path condition setting part was incorrect.";
                case 0x0407D002: return "The public data conversion error occurred, and the conversion of the SFC path condition data was partially wrong.";
                case 0x0407D101: return "PLC data conversion error, error in converting SFC path condition setting.";
                case 0x0407D102: return "PLC data conversion error, error in converting SFC path condition data.";
                case 0x04080001: return "The intermediate code classification is out of range error, and the specified intermediate code classification is out of range.";
                case 0x04080002: return "The extended specification intermediate code classification is out of range error, and the specified extended specification intermediate code is out of range.";
                case 0x04080003: return "There is an error in the number of check device points, and the number of device points is not checked.";
                case 0x04090001: return "The GPP project error, the specified PLC type does not match the GPP project type.";
                case 0x04090002: return "The file type is incorrect. The specified GPP project type does not match the file type.";
                case 0x04090010: return "The converted GPP data is insufficient, no data can be converted. The specified data size is incorrect.";
                case 0x04090011: return "There is not enough space to store the converted data, and there is not enough space to store the converted data.";
                case 0x04090012: return "The conversion of GPP data is incorrect and the converted GPP data is incorrect.";
                case 0x04090110: return "The converted GPP data is insufficient, no data can be converted. The specified data size is incorrect.";
                case 0x04090111: return "There is not enough space to store the converted data, and there is not enough space to store the converted data.";
                case 0x04090112: return "The conversion data is incorrect and the data to be converted is incorrect.";
                case 0x04FFFFFF: return "Other errors";
                case 0x10000001: return "No command error";
                case 0x10000002: return "The DLL communication running MX Component failed.";
                case 0x10000003: return "Open failed (DiskDrive)";
                case 0x10000004: return "Repeat open error Exit the program and restart the IBM-PC/AT compatible computer.";
                case 0x10000005: return "Access file error";
                case 0x10000006: return "The folder name is wrong";
                case 0x10000007: return "An error in denying access to the file";
                case 0x10000008: return "Disk is full error";
                case 0x10000009: return "Error deleting file";
                case 0x1000000A: return "File name error";
                case 0x1000000C: return "Because another program or thread is sending a request, the operation is lost.";
                case 0x1000000D: return "Error creating folder";
                case 0x1000000E: return "Folder/file type error";
                case 0x1000000F: return "Address offset error";
                case 0x10000010: return "Cancel the request and cancel processing.";
                case 0x10000011: return "Protecting memory error";
                case 0x10000012: return "Opening the program without exiting and restarting the IBM-PC/AT compatible computer.";
                case 0x10000013: return "No connection error occurred";
                case 0x10000014: return "Invalid target error";
                case 0x10000015: return "Cancel request failed";
                case 0x10000016: return "Read status failed error";
                case 0x10000017: return "The specified size (number of devices) is not approved.";
                case 0x10000018: return "Devices not registered Exit the program and restart the IBM-PC/AT compatible computer.";
                case 0x10000019: return "Unexecuted array";
                case 0x1000001A: return "No read error occurred";
                case 0x1000001: return "b created markup error";
                case 0x1000001C: return "End of access operation";
                case 0x1000001D: return "Redundant device error";
                case 0x1000001E: return "Search registration failed";
                case 0x1000001F: return "File type error";
                case 0x10000020: return "Device memory type error";
                case 0x10000021: return "Program range error";
                case 0x10000022: return "TEL type error";
                case 0x10000023: return "Access TEL error";
                case 0x10000024: return "Error canceling the tag type";
                case 0x10000030: return "Device repeated registration error";
                case 0x10000031: return "Error in unregistered device";
                case 0x10000032: return "Specified device error";
                case 0x10000033: return "Error in specifying device range";
                case 0x10000034: return "Error writing to file";
                case 0x10000040: return "Starting the server failed";
                case 0x10000041: return "Stop server error, stop server failed.";
                case 0x10000042: return "The server failed to start twice";
                case 0x10000043: return "The server failed to start";
                case 0x10000044: return "Source file timeout error";
                case 0x10000045: return "Server type error";
                case 0x10000046: return "Access to server failed error";
                case 0x10000047: return "The server has been accessed error";
                case 0x10000048: return "Starting the simulator failed";
                case 0x10000049: return "Exit the simulator failed";
                case 0x1000004A: return "The simulator did not start error";
                case 0x1000004: return "B simulator type error";
                case 0x1000004C: return "The simulator is not supported";
                case 0x1000004D: return "The simulator starts twice error";
                case 0x1000004E: return "Error starting shared memory";
                case 0xF0000001: return "No license error, IBM-PC/AT compatible computer is not licensed.";
                case 0xF0000002: return "Error reading data setting, failed to read the logical station number setting data.";
                case 0xF0000003: return "An error has been opened and the open function is executed in the open state.";
                case 0xF0000004: return "The error was not opened and the open function was not executed.";
                case 0xF0000005: return "Initialization error, MX Component internal program initialization failed.";
                case 0xF0000006: return "Protected memory error, protection of MX Component internal memory failed.";
                case 0xF0000007: return "The function is not supported, the function is not supported.";
                case 0xF1000001: return "Character code conversion error, character code conversion (UNICODE ASCII or ASCII code";
                case 0xF1000002: return "The first I/O number was incorrect and the first I/O number value specified was not approved.";
                case 0xF1000003: return "The buffer address is incorrect and the specified buffer address value is not approved.";
                case 0xF1000004: return "The read buffer size is wrong, the buffer is read, and the specified size cannot be obtained.";
                case 0xF1000005: return "The size is wrong, the size specified in the read/write function is abnormal.";
                case 0xF1000006: return "The operation error occurred and the specified remote operation was an outlier.";
                case 0xF1000007: return "The clock data is wrong and the clock data is abnormal.";
                case 0xF1000008: return "The number of registration points of the M monitor is exceeded. The number of device points registered in the EntryDeviceStatus function is blank";
                case 0xF1000009: return "Registered device monitoring data error";
                case 0xF1000010: return "The startup device status monitor processing failed. The end device status monitor processing failed.";
                case 0xF1000011: return "Error in variable data type.";
                case 0xF1000012: return "The time interval value of the device status monitoring exceeds 1 second to 1 hour, and the range (1 to 3600).";
                case 0xF1000013: return "The connection has been made incorrectly, and the connection is repeated after the program runs.";
                case 0xF1000014: return "The connection is repeated after the program is run. The phone number contains characters other than \"0123456789 - *#\".";
                case 0xF1000015: return "The dedicated control failed with an error and the dedicated control failed while executing the connect and disconnect functions.";
                case 0xF1000016: return "The connection phone line is wrong, except for MX Comonent, the phone line is connecting to other applications";
                case 0xF1000017: return "The phone line is not connected incorrectly. The phone line is not connected.";
                case 0xF1000018: return "No phone number error. The phone number is not set.";
                case 0xF1000019: return "No shutdown error, disconnect when open state.";
                case 0xF100001A: return "The connection destination phone line mismatch error. Use a different phone number for the port that is connected to the phone line";
                case 0xF100001: return "b control type mismatch error, for a control type different from a pair of connected telephone lines";
                case 0xF100001C: return "The error has not been disconnected. When the disconnect function is executed on the object connected to the telephone line, it is found.";
                case 0xF100001D: return "No connection error, open before connecting or disconnecting execution.";
                case 0xF100001E: return "serious error";
                case 0xF100001F: return "Setting the open time error, the phone number and port number used to connect and open are set";
                case 0xF2000002: return "An error response from the target phone. May be for the following reasons:";
                case 0xF2000003: return "Invalid data was received. It may be for the following reasons:";
                case 0xF2000004: return "The modem is not responding. It may be for the following reasons:";
                case 0xF2000005: return "The line may not be disconnected. Check the line.";
                case 0xF2000006: return "The personal computer modem did not receive the AT command. It may be for the following reasons:";
                case 0xF2000007: return "The modem did not respond correctly to the standard exit command.";
                case 0xF2000009: return "The modem did not respond correctly to the disconnect line command. Check the modem.";
                case 0xF200000A: return "The object does not receive a signal.,* The receiving settings of the other modem may be incorrect.";
                case 0xF200000: return "b Waiting time to receive a callback timed out.";
                case 0xF200000C: return "Cannot distinguish the passwords of A6TEL, Q6TEL, QJ71C24 units.";
                case 0xF2010001: return "The wait time for disconnecting the callback line is not between 0 and 180 seconds. The delay for performing the callback is not between 0 and 1800 seconds.";
                case 0xF2010002: return "QJ71C24 did not receive the specified connection function. It may be for the following reasons:";
                case 0xF2010003: return "The QJ71C24 does not allow automatic connection (when fixed callback or designated number,).";
                case 0xF2100005: return "The line may not be disconnected.";
                case 0xF2100008: return "The modem has no objection to the data sent from the personal computer.";
                case 0xF2100006: return "The modem did not receive the AT boot command.";
                case 0xF2100007: return "The personal computer modem does not respond to the exit command.";
                //case 0xF21000**: return "The modem is not responding. It may be for the following reasons:";
                //case 0xF21001**: return "A(Q)6TEL/C24 has no response. It may be for the following reasons:";
                //case 0xF202****: return "There is a communication failure. The following reasons can be determined according to the situation.";
                default: return "Unkonw error";
            }
        }
    }
}
